use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::{
    env, fs,
    path::{Component, Path, PathBuf},
};

pub const MODEL_TASK: &str = "zedAndroidPreviewModel";
const MARKER: &str = "# Generated by Android IDE for Compose preview.\n*\n";
const OUTPUT: &str = "ANDROID_IDE_PREVIEW_MODEL=";

// Gradle exposes the evaluated outputs; never guess AGP's version-specific intermediate directories.
const INIT: &str = r#"gradle.projectsEvaluated {
    def overlayPath = System.getProperty('zed.android.preview.overlay')
    def replacements = overlayPath ? new groovy.json.JsonSlurper().parse(new File(overlayPath)) : [:]
    if (overlayPath) {
        gradle.rootProject.allprojects.each { p ->
            p.tasks.matching { it.name.startsWith('compile') && it.name.endsWith('Kotlin') }.configureEach { task ->
                def getter = task.class.methods.find { it.name.startsWith('getSourceFiles') && it.parameterCount == 0 }
                if (!getter) throw new GradleException('This Kotlin plugin cannot preview unsaved sources. Save the files and rebuild previews.')
                def sourceFiles = getter.invoke(task)
                def roots = p.files(sourceFiles.from.toList())
                def original = roots.asFileTree
                // Membership checks must wait until generated-source producers have run.
                def originalFiles = null
                def edited = replacements.collect { path, replacement ->
                    def file = new File(replacement)
                    p.fileTree(file.parentFile).matching {
                        include { entry ->
                            if (entry.file.absolutePath != file.absolutePath) return false
                            if (originalFiles == null) originalFiles = original.files
                            originalFiles.contains(new File(path))
                        }
                    }
                }
                sourceFiles.setFrom(original.matching { exclude { replacements.containsKey(it.file.absolutePath) } }, edited)
            }
        }
    }
    def project = gradle.rootProject.project(System.getProperty('zed.android.module'))
    def variant = System.getProperty('zed.android.variant')
    def capitalized = variant.substring(0, 1).toUpperCase(java.util.Locale.ROOT) + variant.substring(1)
    def javaCompile = project.tasks.named('compile' + capitalized + 'JavaWithJavac')
    def kotlinCompile = project.tasks.named('compile' + capitalized + 'Kotlin')
    def resources = project.tasks.named('process' + capitalized + 'Resources')
    def runtimeArtifacts = project.configurations.getByName(variant + 'RuntimeClasspath').incoming.artifactView {
        attributes.attribute(org.gradle.api.artifacts.type.ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, 'android-classes-jar')
    }
    def runtime = runtimeArtifacts.files
    project.tasks.register('zedAndroidPreviewModel') {
        dependsOn(javaCompile, kotlinCompile, resources)
        inputs.files(runtime)
        doLast {
            def resourceClasses = resources.get().outputs.files.files.findAll { it.isFile() && it.name == 'R.jar' }
            if (resourceClasses.size() != 1) throw new GradleException('Expected one runtime R.jar from ' + resources.name)
            def classes = [kotlinCompile.get().destinationDirectory.get().asFile, javaCompile.get().destinationDirectory.get().asFile] + resourceClasses
            classes = classes.findAll { it.exists() }
            println('ANDROID_IDE_PREVIEW_MODEL=' + groovy.json.JsonOutput.toJson([
                module: project.path, variant: variant, namespace: project.android.namespace,
                classPath: (runtime.files + classes).unique()*.absolutePath,
                projectClassPath: classes*.absolutePath,
                previewClassPath: (classes + runtimeArtifacts.artifacts.artifacts.findAll {
                    it.id.componentIdentifier instanceof org.gradle.api.artifacts.component.ProjectComponentIdentifier
                }*.file).unique()*.absolutePath,
                sourceFiles: gradle.taskGraph.allTasks.findAll {
                    it.name.startsWith('compile') && (it.name.endsWith('Kotlin') || it.name.endsWith('JavaWithJavac'))
                }.collectMany { task ->
                    def sources = task.name.endsWith('Kotlin') ? task.sources.files : task.source.files
                    sources.collect { file ->
                        def replacement = replacements.find { original, edited -> new File(edited).absolutePath == file.absolutePath }
                        replacement ? new File(replacement.key) : file
                    }
                }.findAll { it.isFile() }.unique()*.absolutePath
            ]))
        }
    }
}
"#;

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Model {
    pub module: String,
    pub variant: String,
    pub namespace: String,
    pub class_path: Vec<PathBuf>,
    pub project_class_path: Vec<PathBuf>,
    #[serde(default)]
    pub source_files: Vec<PathBuf>,
    #[serde(default)]
    pub preview_class_path: Vec<PathBuf>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Preview {
    #[serde(rename = "methodFQN")]
    pub method: String,
    #[serde(rename = "previewId")]
    pub id: String,
    #[serde(rename = "sourceFile", default)]
    pub source_file: String,
    #[serde(rename = "packageName", default)]
    pub package_name: String,
    #[serde(flatten)]
    pub parameters: serde_json::Map<String, Value>,
}

impl Preview {
    pub fn belongs_to(&self, path: &Path, package: &str) -> bool {
        path.file_name()
            .is_some_and(|name| name == self.source_file.as_str())
            && self.package_name == package
    }

    pub fn label(&self) -> String {
        let name = self
            .parameters
            .get("previewParams")
            .and_then(|parameters| parameters.get("name"))
            .and_then(Value::as_str)
            .filter(|name| !name.is_empty());
        let method = self.method.rsplit('.').next().unwrap_or(&self.method);
        match name {
            Some(name) => format!("{name} · {method}"),
            None => method.to_owned(),
        }
    }
}

pub fn installation() -> Result<PathBuf> {
    let directory = env::var_os("ANDROID_IDE_COMPOSE_PREVIEW").map(PathBuf::from)
        .context("Run script/install-android-preview, then relaunch script/android-ide to enable Compose preview.")?;
    ensure!(
        directory.is_absolute(),
        "ANDROID_IDE_COMPOSE_PREVIEW must be an absolute directory"
    );
    for file in [
        "PreviewBridge.class",
        "renderer.jar",
        "layoutlib.jar",
        "layoutlib/data/framework_res.jar",
    ] {
        ensure!(
            directory.join(file).is_file(),
            "Compose preview installation is incomplete: {file}"
        );
    }
    ensure!(
        fs::read_to_string(directory.join(".protocol")).is_ok_and(|version| version.trim() == "2"),
        "Update Compose preview tools with script/install-android-preview, then relaunch script/android-ide."
    );
    Ok(directory)
}

pub fn prepare(root: &Path) -> Result<PathBuf> {
    ensure_directory(&root.join(".koda"))?;
    let cache = root.join(".koda/android-preview");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == MARKER,
            "The .koda/android-preview directory contains unmanaged files. Move it aside before rendering previews."
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), MARKER, false)?;
    }
    atomic_write(&cache.join("export.gradle"), INIT, false)?;
    Ok(cache)
}

pub fn parse_model(output: &str, root: &Path, target: &AndroidTarget) -> Result<Model> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(OUTPUT));
    let model: Model = serde_json::from_str(
        records
            .next()
            .context("Gradle returned no Compose preview model")?,
    )?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Compose preview models"
    );
    ensure!(
        model.module == target.module && model.variant == target.variant,
        "The Compose model belongs to a different variant"
    );
    ensure!(
        !model.namespace.is_empty()
            && !model.class_path.is_empty()
            && !model.project_class_path.is_empty(),
        "The Compose model has no namespace or compiled classes"
    );
    let root = root.canonicalize()?;
    for path in &model.class_path {
        ensure!(
            path.is_absolute() && path.exists(),
            "Missing preview classpath entry: {}",
            path.display()
        );
    }
    for path in &model.project_class_path {
        ensure!(
            path.is_absolute()
                && path.canonicalize()?.starts_with(&root)
                && model.class_path.contains(path),
            "Preview project classes must belong to the selected project"
        );
    }
    ensure!(
        model
            .preview_class_path
            .iter()
            .all(|path| model.class_path.contains(path)),
        "Preview discovery entries must belong to the compiled classpath"
    );
    Ok(model)
}

pub fn write_source_overlay(
    output: &Path,
    sources: &[(PathBuf, String)],
) -> Result<Option<PathBuf>> {
    if sources.is_empty() {
        return Ok(None);
    }
    let mut replacements = serde_json::Map::new();
    for (index, (source, text)) in sources.iter().enumerate() {
        let name = source
            .file_name()
            .context("A preview source has no filename")?;
        let directory = output.join("sources").join(index.to_string());
        fs::create_dir_all(&directory)?;
        let replacement = directory.join(name);
        fs::write(&replacement, text)?;
        replacements.insert(source.to_string_lossy().into_owned(), json!(replacement));
    }
    let manifest = output.join("sources.json");
    fs::write(&manifest, serde_json::to_vec(&replacements)?)?;
    Ok(Some(manifest))
}

pub fn bridge_arguments(
    installation: &Path,
    operation: &str,
    input: &Path,
    output: Option<&Path>,
) -> Result<Vec<String>> {
    let classpath = env::join_paths([
        installation.to_path_buf(),
        installation.join("renderer.jar"),
        installation.join("layoutlib.jar"),
    ])?;
    let mut args = vec![
        "-Xmx2g".into(),
        "-Djava.awt.headless=true".into(),
        // The fast loader hardcodes unrelocated factories; layoutlib relocates coroutines.
        "-Dkotlinx.coroutines.fast.service.loader=false".into(),
        "--enable-native-access=ALL-UNNAMED".into(),
        "-cp".into(),
        classpath.to_string_lossy().into_owned(),
        "PreviewBridge".into(),
        operation.into(),
        input.to_string_lossy().into_owned(),
    ];
    if let Some(output) = output {
        args.push(output.to_string_lossy().into_owned());
    }
    Ok(args)
}

pub fn read_previews(path: &Path) -> Result<Vec<Preview>> {
    let previews: Vec<Preview> = serde_json::from_str(&fs::read_to_string(path)?)?;
    for preview in &previews {
        ensure!(
            !preview.id.is_empty() && !preview.method.is_empty(),
            "Preview discovery returned an invalid method"
        );
    }
    Ok(previews)
}

pub fn render_settings(
    model: &Model,
    previews: &[Preview],
    apk: &Path,
    installation: &Path,
    output: &Path,
) -> Value {
    let screenshots = previews
        .iter()
        .map(|preview| {
            let mut screenshot = json!({"methodFQN": preview.method, "previewId": preview.id});
            // alpha15's streaming JSON reader cannot skip unknown screenshot fields.
            for field in ["previewParams", "methodParams", "previewWrapperFqn"] {
                if let Some(value) = preview.parameters.get(field) {
                    screenshot[field] = value.clone();
                }
            }
            screenshot
        })
        .collect::<Vec<_>>();
    json!({"namespace": model.namespace, "classPath": model.class_path, "projectClassPath": model.project_class_path,
        "layoutlibPath": installation.join("layoutlib"), "resourceApkPath": apk,
        "outputFolder": output, "metaDataFolder": output.join("metadata"), "resultsFilePath": output.join("results.json"), "screenshots": screenshots})
}

fn render_failure(error: &Value) -> String {
    error
        .as_str()
        .or_else(|| {
            error
                .get("message")
                .and_then(Value::as_str)
                .filter(|message| !message.is_empty())
        })
        .or_else(|| {
            error
                .get("problems")
                .and_then(Value::as_array)?
                .iter()
                .find_map(|problem| {
                    problem
                        .get("html")
                        .and_then(Value::as_str)
                        .filter(|message| !message.is_empty())
                })
        })
        .or_else(|| {
            error
                .get("stackTrace")
                .and_then(Value::as_str)
                .filter(|message| !message.is_empty())
        })
        .map(|message| {
            let message = message.lines().take(8).collect::<Vec<_>>().join("\n");
            let message = regex::Regex::new(r"<[^>]*>")
                .map(|pattern| pattern.replace_all(&message, "").into_owned())
                .unwrap_or(message);
            message.chars().take(2000).collect()
        })
        .unwrap_or_else(|| error.to_string())
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ComposeNode {
    pub name: String,
    pub file_name: String,
    pub line_number: i32,
    pub package_hash: i32,
    pub bounds: [i32; 4],
    pub depth: u32,
    #[serde(skip)]
    pub source_path: Option<PathBuf>,
}

impl ComposeNode {
    pub fn contains(&self, x: f32, y: f32) -> bool {
        let [left, top, right, bottom] = self.bounds;
        right > left
            && bottom > top
            && x >= left as f32
            && x < right as f32
            && y >= top as f32
            && y < bottom as f32
    }
}

#[derive(Clone, Debug)]
pub struct RenderedPreview {
    pub id: String,
    pub parameter_index: usize,
    pub image: Option<PathBuf>,
    pub width: u32,
    pub height: u32,
    pub nodes: Vec<ComposeNode>,
    pub error: Option<String>,
    pub inspection_error: Option<String>,
}

pub fn hit_test(nodes: &[ComposeNode], x: f32, y: f32) -> Option<usize> {
    nodes
        .iter()
        .enumerate()
        .filter(|(_, node)| {
            node.source_path.is_some() && node.line_number > 0 && node.contains(x, y)
        })
        .max_by_key(|(_, node)| (node.depth, node.line_number))
        .map(|(index, _)| index)
}

// Compose uses the absolute Java string hash, including UTF-16 surrogate pairs.
pub fn package_hash(package: &str) -> i32 {
    package
        .encode_utf16()
        .fold(0i32, |hash, unit| {
            hash.wrapping_mul(31).wrapping_add(unit as i32)
        })
        .wrapping_abs()
}

pub fn kotlin_package(source: &str) -> String {
    let mut text = source.as_bytes().to_vec();
    let mut offset = 0;
    while offset < text.len() {
        let start = offset;
        if text.get(offset..offset + 2) == Some(b"//") {
            while offset < text.len() && text[offset] != b'\n' {
                offset += 1;
            }
        } else if text.get(offset..offset + 2) == Some(b"/*") {
            offset += 2;
            let mut depth = 1;
            while offset < text.len() && depth > 0 {
                if text.get(offset..offset + 2) == Some(b"/*") {
                    depth += 1;
                    offset += 2;
                } else if text.get(offset..offset + 2) == Some(b"*/") {
                    depth -= 1;
                    offset += 2;
                } else {
                    offset += 1;
                }
            }
        } else if text[offset] == b'"' || text[offset] == b'\'' {
            let quote = text[offset];
            let triple = text.get(offset..offset + 3) == Some(b"\"\"\"");
            offset += if triple { 3 } else { 1 };
            while offset < text.len() {
                if triple && text.get(offset..offset + 3) == Some(b"\"\"\"") {
                    offset += 3;
                    break;
                }
                if !triple && text[offset] == quote {
                    offset += 1;
                    break;
                }
                if !triple && text[offset] == b'\\' {
                    offset += 1;
                }
                offset = (offset + 1).min(text.len());
            }
        } else {
            offset += 1;
            continue;
        }
        for byte in &mut text[start..offset] {
            if *byte != b'\n' {
                *byte = b' ';
            }
        }
    }
    let text = String::from_utf8_lossy(&text);
    for line in text.lines() {
        if let Some(package) = line
            .trim_start_matches('\u{feff}')
            .trim()
            .strip_prefix("package")
            && package.starts_with(char::is_whitespace)
        {
            return package
                .trim()
                .trim_end_matches(';')
                .split('.')
                .map(|part| part.trim().trim_matches('`'))
                .collect::<Vec<_>>()
                .join(".");
        }
    }
    String::new()
}

pub struct SourceIndex {
    files: Vec<(PathBuf, i32)>,
}

impl SourceIndex {
    pub fn new(
        root: &Path,
        sources: &[PathBuf],
        overlays: &[(PathBuf, String)],
        names: &std::collections::BTreeSet<String>,
    ) -> Result<Self> {
        let root = root.canonicalize()?;
        let files = sources
            .iter()
            .filter_map(|path| path.canonicalize().ok())
            .filter(|path| path.starts_with(&root) && path.is_file())
            .filter(|path| {
                path.file_name()
                    .is_some_and(|name| names.contains(name.to_string_lossy().as_ref()))
            })
            .collect::<std::collections::BTreeSet<_>>();
        Ok(Self {
            files: files
                .into_iter()
                .map(|path| {
                    let text = match overlays.iter().find(|(source, _)| source == &path) {
                        Some((_, text)) => text.clone(),
                        None => fs::read_to_string(&path)?,
                    };
                    let hash = package_hash(&kotlin_package(&text));
                    Ok((path, hash))
                })
                .collect::<Result<_>>()?,
        })
    }

    pub fn resolve(&self, node: &ComposeNode, current_file: &Path) -> Option<PathBuf> {
        let matches = self
            .files
            .iter()
            .filter(|(path, hash)| {
                path.file_name()
                    .is_some_and(|name| name == node.file_name.as_str())
                    && (node.package_hash == -1 || node.package_hash == *hash)
            })
            .map(|(path, _)| path);
        let mut candidates = matches.collect::<Vec<_>>();
        if let Some(path) = candidates
            .iter()
            .find(|path| path.as_path() == current_file)
        {
            return Some((*path).clone());
        }
        if candidates.len() == 1 {
            return candidates.pop().cloned();
        }
        None
    }
}

pub fn rendered_previews(output: &Path, previews: &[Preview]) -> Result<Vec<RenderedPreview>> {
    let results: Value = serde_json::from_str(
        &fs::read_to_string(output.join("results.json"))
            .context("The Compose renderer returned no result")?,
    )?;
    ensure!(
        results["globalError"].is_null(),
        "Compose rendering failed: {}",
        render_failure(&results["globalError"])
    );
    let results = results["screenshotResults"]
        .as_array()
        .context("Invalid Compose rendering result")?;
    ensure!(
        !results.is_empty() || previews.is_empty(),
        "The Compose renderer produced no previews"
    );
    let output = output.canonicalize()?;
    let mut seen = std::collections::BTreeSet::new();
    let mut gallery_pixels = 0u64;
    results.iter().map(|result| {
        let id = result["previewId"].as_str().context("Missing preview identity")?;
        ensure!(previews.iter().any(|preview| preview.id == id), "Unknown rendered preview: {id}");
        let parameter_index = result["parameterIndex"].as_u64().context("Missing preview parameter index")? as usize;
        ensure!(seen.insert((id.to_owned(), parameter_index)), "Duplicate rendered preview");
        let error = (!result["error"].is_null()).then(|| render_failure(&result["error"]));
        let width = result["width"].as_u64().unwrap_or(0);
        let height = result["height"].as_u64().unwrap_or(0);
        ensure!(width <= 16384 && height <= 16384, "Invalid preview dimensions");
        let image = if error.is_none() {
            ensure!(width > 0 && height > 0 && width <= 16384 && height <= 16384, "Invalid preview dimensions");
            gallery_pixels = gallery_pixels.saturating_add(width.saturating_mul(height));
            ensure!(gallery_pixels <= 64 * 1024 * 1024, "Preview images exceed the 256 MiB gallery budget. Reduce preview dimensions or parameter counts.");
            let relative = Path::new(result["imagePath"].as_str().context("Missing preview image path")?);
            ensure!(!relative.as_os_str().is_empty() && relative.components().all(|part| matches!(part, Component::Normal(_))), "Preview image must stay inside its output directory");
            let image = output.join(relative).canonicalize()?;
            ensure!(image.starts_with(&output) && image.is_file() && image.extension().is_some_and(|extension| extension == "png"), "Invalid Compose preview image");
            Some(image)
        } else { None };
        let nodes: Vec<ComposeNode> = serde_json::from_value(result.get("nodes").cloned().unwrap_or_else(|| json!([])))?;
        ensure!(nodes.len() <= 10000 && nodes.iter().all(|node| node.depth <= 1000), "Preview hierarchy is too large");
        Ok(RenderedPreview { id: id.to_owned(), parameter_index, image, width: width as u32, height: height as u32, nodes, error,
            inspection_error: result["inspectionError"].as_str().map(str::to_owned) })
    }).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_preview_model_results_and_owned_cache() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        let cache = prepare(root)?;
        assert_eq!(prepare(root)?, cache);
        let classes = root.join("classes");
        fs::create_dir(&classes)?;
        let target = AndroidTarget {
            module: ":mobile".into(),
            variant: "demoDebug".into(),
            output_listing: root.join("metadata.json"),
        };
        let model = json!({"module": ":mobile", "variant":"demoDebug", "namespace":"dev.sample", "classPath":[classes], "projectClassPath":[classes]});
        let record = format!("{OUTPUT}{model}");
        assert_eq!(parse_model(&record, root, &target)?.variant, "demoDebug");
        assert!(parse_model(&format!("{record}\n{record}"), root, &target).is_err());
        let mut wrong = model;
        wrong["variant"] = "fullDebug".into();
        assert!(parse_model(&format!("{OUTPUT}{wrong}"), root, &target).is_err());
        let output = root.join("output");
        fs::create_dir(&output)?;
        fs::write(output.join("sample.png"), b"PNG fixture")?;
        assert_eq!(
            render_failure(&json!({"message":"Preview failure", "stackTrace":"Long stack"})),
            "Preview failure"
        );
        let preview: Preview = serde_json::from_value(
            json!({"methodFQN":"sample.MainKt.Preview", "previewId":"preview", "sourceFile":"Main.kt"}),
        )?;
        let results = output.join("results.json");
        fs::write(
            &results,
            r#"{"screenshotResults":[{"previewId":"preview","parameterIndex":0,"imagePath":"sample.png","width":1,"height":1}]}"#,
        )?;
        assert_eq!(
            rendered_previews(&output, std::slice::from_ref(&preview))?
                .remove(0)
                .image
                .context("Image")?,
            output.join("sample.png").canonicalize()?
        );
        for invalid in [
            r#"{"globalError":"failed"}"#,
            r#"{"screenshotResults":[]}"#,
            r#"{"screenshotResults":[{"imagePath":"../outside.png"}]}"#,
            r#"{"screenshotResults":[{"previewId":"unknown","parameterIndex":0,"imagePath":"sample.png","width":1,"height":1}]}"#,
        ] {
            fs::write(&results, invalid)?;
            assert!(rendered_previews(&output, std::slice::from_ref(&preview)).is_err());
        }
        fs::write(cache.join(".gitignore"), "User files")?;
        assert!(prepare(root).is_err());
        Ok(())
    }

    #[test]
    fn filters_by_bytecode_source_file_and_handles_kotlin_file_facades() -> Result<()> {
        let preview: Preview = serde_json::from_value(
            json!({"methodFQN":"sample.CustomFacade.Greeting", "previewId":"greeting", "sourceFile":"Main.kt", "packageName":"sample"}),
        )?;
        assert!(preview.belongs_to(Path::new("/src/Main.kt"), "sample"));
        assert!(!preview.belongs_to(Path::new("/src/Main.kt"), "other"));
        assert!(!preview.belongs_to(Path::new("/src/CustomFacade.kt"), "sample"));
        assert_eq!(
            kotlin_package(
                "/* package wrong\n /* nested */ */\n@file:JvmName(\"package wrong\")\npackage sample . `when` // comment\n"
            ),
            "sample.when"
        );
        assert_eq!(
            kotlin_package("val text = \"\"\"\npackage fake\n\"\"\"\n"),
            ""
        );
        assert_eq!(
            package_hash("sample"),
            "sample"
                .encode_utf16()
                .fold(0i32, |hash, value| hash
                    .wrapping_mul(31)
                    .wrapping_add(value as i32))
                .wrapping_abs()
        );
        Ok(())
    }

    #[test]
    fn source_locations_disambiguate_packages_and_unsaved_overlays() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path();
        let first = root.join("first");
        let second = root.join("second");
        fs::create_dir(&first)?;
        fs::create_dir(&second)?;
        let current = first.join("Main.kt");
        let other = second.join("Main.kt");
        fs::write(&current, "package first\n")?;
        fs::write(&other, "package second\n")?;
        let index = SourceIndex::new(
            root,
            &[current.clone(), other.clone()],
            &[(current.clone(), "package unsaved\n".into())],
            &["Main.kt".into()].into_iter().collect(),
        )?;
        let mut node = ComposeNode {
            name: "Text".into(),
            file_name: "Main.kt".into(),
            line_number: 4,
            package_hash: package_hash("second"),
            bounds: [0, 0, 100, 100],
            depth: 0,
            source_path: None,
        };
        assert_eq!(index.resolve(&node, &current), Some(other));
        node.package_hash = package_hash("unsaved");
        assert_eq!(index.resolve(&node, &current), Some(current.clone()));
        node.package_hash = package_hash("missing");
        assert!(index.resolve(&node, &current).is_none());
        node.source_path = Some(current);
        node.package_hash = package_hash("unsaved");
        let mut child = node.clone();
        child.bounds = [20, 20, 40, 40];
        child.depth = 2;
        child.line_number = 9;
        let mut framework = child.clone();
        framework.depth = 4;
        framework.source_path = None;
        let nodes = [node, child, framework];
        assert_eq!(hit_test(&nodes, 25., 25.), Some(1));
        assert_eq!(hit_test(&nodes, 50., 50.), Some(0));
        assert_eq!(hit_test(&nodes, 100., 50.), None);
        assert_eq!(hit_test(&nodes, f32::NAN, 50.), None);
        Ok(())
    }

    #[test]
    fn temporary_source_overlays_preserve_files_and_duplicate_filenames() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let first = temporary.path().join("Main.kt");
        fs::write(&first, "saved")?;
        let sources = [
            (first.clone(), "edited".into()),
            (temporary.path().join("other/Main.kt"), "other".into()),
        ];
        let manifest = write_source_overlay(temporary.path(), &sources)?.context("Manifest")?;
        let replacements: std::collections::HashMap<PathBuf, PathBuf> =
            serde_json::from_slice(&fs::read(manifest)?)?;
        assert_eq!(fs::read_to_string(&first)?, "saved");
        for (path, text) in sources {
            assert_eq!(fs::read_to_string(&replacements[&path])?, text);
            assert_eq!(replacements[&path].file_name(), path.file_name());
        }
        Ok(())
    }

    #[test]
    fn gallery_keeps_parameter_values_and_individual_render_failures() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let previews: Vec<Preview> = serde_json::from_value(json!([
            {"methodFQN":"sample.MainKt.Provider", "previewId":"provider"},
            {"methodFQN":"sample.MainKt.Broken", "previewId":"broken"}
        ]))?;
        fs::write(temporary.path().join("first.png"), b"PNG fixture")?;
        let manifest = json!({"screenshotResults":[
            {"previewId":"provider", "parameterIndex":0,"imagePath":"first.png","width":10,"height":20},
            {"previewId":"provider", "parameterIndex":1,"imagePath":"first.png","width":10,"height":20},
            {"previewId":"broken", "parameterIndex":0,"error":{"message":"Composable crashed"}}
        ]});
        fs::write(
            temporary.path().join("results.json"),
            serde_json::to_vec(&manifest)?,
        )?;
        let gallery = rendered_previews(temporary.path(), &previews)?;
        assert_eq!(gallery.len(), 3);
        assert!(gallery[0].image.is_some() && gallery[1].image.is_some());
        assert_eq!(gallery[2].error.as_deref(), Some("Composable crashed"));
        assert!(gallery[2].image.is_none());
        for (key, value) in [
            ("imagePath", json!("../escape.png")),
            ("width", json!(20000)),
        ] {
            let mut invalid = manifest.clone();
            invalid["screenshotResults"][0][key] = value;
            fs::write(
                temporary.path().join("results.json"),
                serde_json::to_vec(&invalid)?,
            )?;
            assert!(rendered_previews(temporary.path(), &previews).is_err());
        }
        Ok(())
    }

    #[test]
    fn renderer_configuration_omits_discovery_metadata() -> Result<()> {
        let preview: Preview = serde_json::from_value(json!({
            "methodFQN":"sample.MainKt.Provider", "previewId":"provider",
            "sourceFile":"Main.kt", "packageName":"sample", "futureMetadata":"value",
            "previewParams":{"name":"Named"},
            "methodParams":[{"provider":"sample.Names", "limit":"2"}]
        }))?;
        let model = Model {
            module: ":app".into(),
            variant: "debug".into(),
            namespace: "sample".into(),
            class_path: Vec::new(),
            project_class_path: Vec::new(),
            preview_class_path: Vec::new(),
            source_files: Vec::new(),
        };
        let settings = render_settings(
            &model,
            &[preview],
            Path::new("app.apk"),
            Path::new("tools"),
            Path::new("output"),
        );
        let screenshot = &settings["screenshots"][0];
        assert_eq!(screenshot["methodParams"][0]["provider"], "sample.Names");
        for field in ["sourceFile", "packageName", "futureMetadata"] {
            assert!(screenshot.get(field).is_none());
        }
        assert_eq!(
            render_failure(
                &json!({"message":"", "stackTrace":"", "problems":[{"html":"Rendering failed: <b>Expected failure</b>"}]})
            ),
            "Rendering failed: Expected failure"
        );
        Ok(())
    }
}
