use crate::{
    AndroidTarget,
    kotlin::{atomic_write, ensure_directory},
};
use anyhow::{Context as _, Result, ensure};
use serde::{Deserialize, Serialize};
use std::{
    cmp::Ordering,
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Component as PathComponent, Path, PathBuf},
    sync::Arc,
};

pub const MODEL_TASK: &str = "kodaAndroidProjectModel";
pub const MODEL_OUTPUT_PREFIX: &str = "KODA_ANDROID_PROJECT_MODEL=";
const OUTPUT: &str = MODEL_OUTPUT_PREFIX;
const MARKER: &str = "# Generated by Koda for Android project models.\n*\n";
const EXPORT: &str = include_str!("project_model.gradle");

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Deserialize, Serialize)]
pub struct VariantId {
    pub module: String,
    pub variant: String,
}

impl VariantId {
    pub fn label(&self) -> String {
        format!("{} · {}", self.module, self.variant)
    }

    /// A Gradle task identity does not require an application APK output.
    pub fn gradle_task(&self, prefix: &str, suffix: &str) -> String {
        crate::gradle_variant_task(&self.module, &self.variant, prefix, suffix)
    }
}

impl From<&AndroidTarget> for VariantId {
    fn from(target: &AndroidTarget) -> Self {
        Self {
            module: target.module.clone(),
            variant: target.variant.clone(),
        }
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum ModuleKind {
    Application,
    Library,
    DynamicFeature,
    Test,
    Jvm,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceScope {
    Main,
    UnitTest,
    AndroidTest,
    TestFixtures,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceKind {
    Java,
    Kotlin,
    Resources,
    Manifest,
    Assets,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceProviderOrder {
    /// The evaluated Gradle source-set container's iteration order, which can
    /// differ from both textual declarations and Studio's active overlay order.
    GradleSourceSetIteration,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SourceProviderRootKind {
    Java,
    Kotlin,
    /// Android `res` directories, rather than JVM classpath resources.
    Resources,
    Aidl,
    Renderscript,
    Assets,
    JniLibs,
    Manifest,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceProviderRoot {
    pub path: PathBuf,
    pub kind: SourceProviderRootKind,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceProvider {
    pub name: String,
    pub roots: Vec<SourceProviderRoot>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceProviderCatalog {
    pub order: SourceProviderOrder,
    pub providers: Vec<SourceProvider>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(tag = "status", content = "value", rename_all = "camelCase")]
pub enum EvaluatedProviderMetadata {
    Available(ProviderToolingModel),
    Unavailable(ProviderMetadataUnavailable),
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ProviderMetadataUnavailable {
    pub capability: String,
    pub detail: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderToolingModel {
    pub version: u32,
    pub agp_version: String,
    pub model_producer: ProviderModelVersion,
    pub default_source_set: Option<ProviderContainer>,
    pub build_types: Vec<ProviderDimension>,
    pub product_flavors: Vec<ProviderDimension>,
    pub variants: Vec<ProviderVariant>,
    /// None means the tooling model did not expose suite definitions.
    pub test_suites: Option<Vec<ProviderSuiteDefinition>>,
    pub native_membership: Option<Vec<NativeProviderMembership>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ProviderModelVersion {
    pub major: u32,
    pub minor: u32,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderContainer {
    pub main: Option<SourceProvider>,
    pub host_tests: Vec<ArtifactSourceProvider>,
    pub device_tests: Vec<ArtifactSourceProvider>,
    pub fixtures: Option<SourceProvider>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ArtifactSourceProvider {
    pub artifact: String,
    pub provider: SourceProvider,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ProviderDimension {
    /// Identity from the explicitly typed model container, never a directory name.
    pub name: Option<String>,
    pub container: ProviderContainer,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderArtifact {
    pub multi_flavor: Option<SourceProvider>,
    pub variant: Option<SourceProvider>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct NamedProviderArtifact {
    pub artifact: String,
    pub sources: ProviderArtifact,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProviderVariant {
    pub name: String,
    pub build_type: Option<String>,
    pub product_flavors: Vec<String>,
    pub main: ProviderArtifact,
    pub host_tests: Vec<NamedProviderArtifact>,
    pub device_tests: Vec<NamedProviderArtifact>,
    pub fixtures: Option<ProviderArtifact>,
    pub test_suites: Option<Vec<String>>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
pub struct ProviderSuiteDefinition {
    pub name: String,
    /// A known suite with an unsupported source model remains explicit.
    pub providers: Option<Vec<SourceProvider>>,
}

#[derive(Clone, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct NativeProviderMembership {
    pub variant: String,
    pub component: String,
    pub artifact: String,
    pub order: NativeProviderOrder,
    /// This is AGP's increasing-precedence order, which reverses flavors.
    /// Missing capability stays unknown, rather than becoming an empty list.
    pub providers: Option<Vec<String>>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum NativeProviderOrder {
    /// The native SourcesImpl getter, not Studio's provider collector.
    AgpSourceProviderNames,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SourceRoot {
    pub path: PathBuf,
    pub kind: SourceKind,
    pub generated: bool,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum Dependency {
    Project { module: String, variant: String },
    External { coordinate: String },
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Component {
    pub name: String,
    #[serde(default)]
    pub namespace: Option<String>,
    pub scope: SourceScope,
    pub sources: Vec<SourceRoot>,
    pub dependencies: Vec<Dependency>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Variant {
    pub name: String,
    pub components: Vec<Component>,
    pub output_listing: Option<PathBuf>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Module {
    pub path: String,
    pub directory: PathBuf,
    pub namespace: Option<String>,
    pub kind: ModuleKind,
    #[serde(default)]
    pub default_variant: Option<String>,
    /// Evaluated Android DSL facts. Missing legacy or unsupported metadata stays unknown.
    #[serde(default)]
    pub source_providers: Option<SourceProviderCatalog>,
    #[serde(default)]
    pub evaluated_providers: Option<EvaluatedProviderMetadata>,
    pub variants: Vec<Variant>,
}

impl Module {
    /// Configured provider candidates in their reported order, without choosing an
    /// overlay winner. A source-set-iteration catalog does not establish Android
    /// Studio's active-provider order, membership, or existing virtual-file roots.
    pub fn source_provider_candidates(&self, path: &Path) -> Option<Vec<&SourceProvider>> {
        Some(
            self.source_providers
                .as_ref()?
                .providers
                .iter()
                .filter(|provider| {
                    provider.roots.iter().any(|root| {
                        if root.kind == SourceProviderRootKind::Manifest {
                            path == root.path || root.path.parent() == Some(path)
                        } else {
                            path.starts_with(&root.path)
                        }
                    })
                })
                .collect(),
        )
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProjectModel {
    pub version: u32,
    pub root: PathBuf,
    pub modules: Vec<Module>,
    pub diagnostics: Vec<String>,
}

#[derive(Deserialize)]
struct ExportedProjectModel {
    version: u32,
    root: PathBuf,
    modules: Vec<ExportedModule>,
    diagnostics: Vec<String>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct ExportedModule {
    path: String,
    directory: PathBuf,
    namespace: Option<String>,
    kind: ModuleKind,
    #[serde(default)]
    default_variant: Option<String>,
    #[serde(default)]
    source_providers: Option<SourceProviderCatalog>,
    #[serde(default)]
    evaluated_providers: Option<EvaluatedProviderMetadata>,
    variants: Vec<Variant>,
    #[serde(default)]
    default_variant_selection: Option<DefaultVariantSelection>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct DefaultVariantSelection {
    multiplatform: bool,
    preferred_build_types: BTreeSet<String>,
    preferred_product_flavors: BTreeSet<String>,
    variants: Vec<VariantDefinition>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct VariantDefinition {
    name: String,
    build_type: Option<String>,
    product_flavors: Vec<String>,
}

// Adapted from AOSP DefaultVariants.kt, Copyright (C) 2022 The Android Open
// Source Project, Apache-2.0. Original source and notices are retained in
// test_data/default_variants; provenance is in docs/android-studio/ports/default-variants.json.
fn default_variant<'a>(
    variants: &'a [VariantDefinition],
    preferred_build_types: &BTreeSet<String>,
    preferred_product_flavors: &BTreeSet<String>,
) -> Option<&'a str> {
    let dimensions = variants
        .iter()
        .map(|variant| variant.product_flavors.len())
        .min()?;
    let compare_flavors = |left: &VariantDefinition, right: &VariantDefinition, preferred: bool| {
        left.product_flavors
            .iter()
            .zip(&right.product_flavors)
            .take(dimensions)
            .map(|(left, right)| {
                if preferred {
                    (!preferred_product_flavors.contains(left))
                        .cmp(&!preferred_product_flavors.contains(right))
                } else {
                    left.encode_utf16().cmp(right.encode_utf16())
                }
            })
            .find(|ordering| *ordering != Ordering::Equal)
            .unwrap_or(Ordering::Equal)
    };
    variants
        .iter()
        .reduce(|left, right| {
            let preferred_build_type = |variant: &VariantDefinition| {
                variant
                    .build_type
                    .as_ref()
                    .is_some_and(|build_type| preferred_build_types.contains(build_type))
            };
            let ordering = (!preferred_build_type(left))
                .cmp(&!preferred_build_type(right))
                .then_with(|| compare_flavors(left, right, true))
                .then_with(|| {
                    (left.build_type.as_deref() != Some("debug"))
                        .cmp(&(right.build_type.as_deref() != Some("debug")))
                })
                .then_with(|| compare_flavors(left, right, false))
                .then_with(|| match (&left.build_type, &right.build_type) {
                    (Some(left), Some(right)) => left.encode_utf16().cmp(right.encode_utf16()),
                    _ => left.build_type.is_some().cmp(&right.build_type.is_some()),
                });
            if ordering == Ordering::Greater {
                right
            } else {
                left
            }
        })
        .map(|variant| variant.name.as_str())
}

impl ExportedModule {
    fn into_module(self) -> Result<Module> {
        let mut module = Module {
            path: self.path,
            directory: self.directory,
            namespace: self.namespace,
            kind: self.kind,
            default_variant: self.default_variant,
            source_providers: self.source_providers,
            evaluated_providers: self.evaluated_providers,
            variants: self.variants,
        };
        if let Some(selection) = self.default_variant_selection {
            ensure!(
                module
                    .variants
                    .iter()
                    .map(|variant| &variant.name)
                    .eq(selection.variants.iter().map(|variant| &variant.name)),
                "Default variant metadata does not match Android module {}",
                module.path
            );
            module.default_variant = if selection.multiplatform {
                selection
                    .variants
                    .first()
                    .map(|variant| variant.name.clone())
            } else {
                default_variant(
                    &selection.variants,
                    &selection.preferred_build_types,
                    &selection.preferred_product_flavors,
                )
                .map(str::to_owned)
            };
        }
        Ok(module)
    }
}

#[derive(Clone, Debug)]
pub struct SelectedProject {
    pub model: Arc<ProjectModel>,
    pub selected: VariantId,
    pub variants: BTreeMap<String, String>,
}

impl ProjectModel {
    pub fn library_variants(&self) -> Vec<VariantId> {
        let mut variants = self
            .modules
            .iter()
            .filter(|module| module.kind == ModuleKind::Library)
            .flat_map(|module| {
                module.variants.iter().map(move |variant| VariantId {
                    module: module.path.clone(),
                    variant: variant.name.clone(),
                })
            })
            .collect::<Vec<_>>();
        variants.sort();
        variants
    }

    pub fn default_library_variant(&self) -> Option<VariantId> {
        self.modules
            .iter()
            .filter(|module| module.kind == ModuleKind::Library)
            .flat_map(|module| module.variants.iter().map(move |variant| (module, variant)))
            .min_by_key(|(module, variant)| {
                (
                    &module.path,
                    module.default_variant.as_ref() != Some(&variant.name),
                    !(variant.name == "debug" || variant.name.ends_with("Debug")),
                    &variant.name,
                )
            })
            .map(|(module, variant)| VariantId {
                module: module.path.clone(),
                variant: variant.name.clone(),
            })
    }

    pub fn default_target(&self) -> Option<AndroidTarget> {
        self.modules
            .iter()
            .filter(|module| module.kind == ModuleKind::Application)
            .filter_map(|module| {
                let default = module.default_variant.as_ref()?;
                let variant = module
                    .variants
                    .iter()
                    .find(|variant| &variant.name == default)?;
                Some((module, variant, variant.output_listing.as_ref()?))
            })
            .min_by_key(|(module, _, _)| &module.path)
            .map(|(module, variant, output_listing)| AndroidTarget {
                module: module.path.clone(),
                variant: variant.name.clone(),
                output_listing: output_listing.clone(),
            })
    }

    pub fn targets(&self) -> Vec<AndroidTarget> {
        let mut targets = self
            .modules
            .iter()
            .filter(|module| module.kind == ModuleKind::Application)
            .flat_map(|module| {
                module.variants.iter().filter_map(|variant| {
                    Some(AndroidTarget {
                        module: module.path.clone(),
                        variant: variant.name.clone(),
                        output_listing: variant.output_listing.clone()?,
                    })
                })
            })
            .collect::<Vec<_>>();
        targets.sort_by(|left, right| {
            (&left.module, &left.variant).cmp(&(&right.module, &right.variant))
        });
        targets
    }

    pub fn variant(&self, id: &VariantId) -> Option<(&Module, &Variant)> {
        let module = self
            .modules
            .iter()
            .find(|module| module.path == id.module)?;
        Some((
            module,
            module
                .variants
                .iter()
                .find(|variant| variant.name == id.variant)?,
        ))
    }

    pub fn select(self: &Arc<Self>, selected: VariantId) -> Result<SelectedProject> {
        let mut variants = BTreeMap::new();
        let mut pending = vec![selected.clone()];
        while let Some(id) = pending.pop() {
            if let Some(previous) = variants.insert(id.module.clone(), id.variant.clone()) {
                ensure!(
                    previous == id.variant,
                    "The selected graph requires multiple variants of {} ({previous}, {}); one active variant cannot represent it",
                    id.module,
                    id.variant
                );
                continue;
            }
            let (_, variant) = self.variant(&id).with_context(|| {
                format!(
                    "Android variant {} in {} is unavailable; sync again",
                    id.variant, id.module
                )
            })?;
            for component in &variant.components {
                for dependency in &component.dependencies {
                    if let Dependency::Project { module, variant } = dependency {
                        pending.push(VariantId {
                            module: module.clone(),
                            variant: variant.clone(),
                        });
                    }
                }
            }
        }
        Ok(SelectedProject {
            model: self.clone(),
            selected,
            variants,
        })
    }
}

impl SelectedProject {
    /// Modules visible to a source component. Test-only edges do not enter a main source scope.
    pub fn visible_modules(&self, owner: &str, scope: SourceScope) -> BTreeSet<String> {
        let mut visible = BTreeSet::new();
        let mut pending = vec![owner.to_owned()];
        while let Some(path) = pending.pop() {
            if !visible.insert(path.clone()) {
                continue;
            }
            let Some((module, variant)) = self.modules().find(|(module, _)| module.path == path)
            else {
                continue;
            };
            for component in &variant.components {
                if component.scope != SourceScope::Main
                    && !(path == owner && component.scope == scope)
                {
                    continue;
                }
                pending.extend(component.dependencies.iter().filter_map(|dependency| {
                    if let Dependency::Project {
                        module: dependency, ..
                    } = dependency
                    {
                        // Features belong to the app package but are not visible to base app sources.
                        let packaged_feature = module.kind == ModuleKind::Application
                            && self.modules().any(|(candidate, _)| {
                                candidate.path == *dependency
                                    && candidate.kind == ModuleKind::DynamicFeature
                            });
                        (!packaged_feature).then(|| dependency.clone())
                    } else {
                        None
                    }
                }));
            }
        }
        visible
    }

    pub fn modules(&self) -> impl Iterator<Item = (&Module, &Variant)> {
        self.variants.iter().filter_map(|(module, variant)| {
            self.model.variant(&VariantId {
                module: module.clone(),
                variant: variant.clone(),
            })
        })
    }

    pub fn projection(&self) -> serde_json::Value {
        serde_json::Value::Array(self.modules().map(|(module, variant)| serde_json::json!({
            "project": module.path, "variant": variant.name, "directory": module.directory,
            "kind": module.kind, "components": variant.components,
        })).collect())
    }

    pub fn kotlin_variants(&self) -> String {
        self.variants
            .iter()
            .filter(|(module, _)| {
                self.model.modules.iter().any(|candidate| {
                    candidate.path == **module && candidate.kind != ModuleKind::Jvm
                })
            })
            .map(|(module, variant)| format!("{module}={variant}"))
            .collect::<Vec<_>>()
            .join(";")
    }

    pub fn validate_target(&self, target: &AndroidTarget) -> Result<()> {
        ensure!(
            self.selected == VariantId::from(target) && self.model.targets().contains(target),
            "The Android target does not belong to the current project model"
        );
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ModelToken {
    generation: u64,
    root: Option<PathBuf>,
}

impl ModelToken {
    pub(crate) fn revision(&self) -> u64 {
        self.generation
    }
}

#[derive(Clone, Default)]
pub struct ModelState {
    generation: u64,
    root: Option<PathBuf>,
    pub model: Option<Arc<ProjectModel>>,
    pub selected: Option<Arc<SelectedProject>>,
    model_revision: Option<u64>,
    evaluated_inputs: Option<Arc<crate::evaluated_tree_inputs::EvaluatedTreeInputs>>,
}

impl ModelState {
    pub fn model_revision(&self) -> Option<u64> {
        self.model_revision
    }

    pub fn evaluated_inputs(
        &self,
    ) -> Option<&Arc<crate::evaluated_tree_inputs::EvaluatedTreeInputs>> {
        self.evaluated_inputs.as_ref()
    }

    pub fn root(&self) -> Option<&Path> {
        self.root.as_deref()
    }

    pub fn token(&self) -> ModelToken {
        ModelToken {
            generation: self.generation,
            root: self.root.clone(),
        }
    }
    pub fn is_current(&self, token: &ModelToken) -> bool {
        self.token() == *token
    }
    pub fn invalidate(&mut self, root: Option<PathBuf>) -> ModelToken {
        self.generation = self.generation.wrapping_add(1);
        self.root = root;
        self.model = None;
        self.selected = None;
        self.model_revision = None;
        self.evaluated_inputs = None;
        self.token()
    }
    pub fn publish(&mut self, token: &ModelToken, model: ProjectModel) -> Result<()> {
        ensure!(
            self.is_current(token)
                && self.root.as_ref().is_some_and(|root| root == &model.root
                    || root.canonicalize().is_ok_and(|root| root == model.root)),
            "Discarded an outdated Android sync result"
        );
        self.model = Some(Arc::new(model));
        self.model_revision = Some(token.revision());
        self.evaluated_inputs = None;
        Ok(())
    }

    pub fn publish_evaluated(
        &mut self,
        token: &ModelToken,
        capture: crate::evaluated_tree_inputs::EvaluatedTreeInputs,
    ) -> Result<()> {
        ensure!(
            self.is_current(token)
                && capture.token() == token
                && self
                    .root
                    .as_ref()
                    .is_some_and(|root| root == &capture.model().root
                        || root
                            .canonicalize()
                            .is_ok_and(|root| root == capture.model().root)),
            "Discarded an outdated evaluated Android sync result"
        );
        self.model = Some(capture.model().clone());
        self.selected = None;
        self.model_revision = Some(token.revision());
        self.evaluated_inputs = Some(Arc::new(capture));
        Ok(())
    }
    pub fn select(&mut self, id: Option<VariantId>) -> Result<()> {
        self.generation = self.generation.wrapping_add(1);
        self.selected = None;
        if let Some(id) = id {
            self.selected = Some(Arc::new(
                self.model
                    .as_ref()
                    .context("Sync the Android project first")?
                    .select(id)?,
            ));
        }
        Ok(())
    }
}

fn valid_module(name: &str) -> bool {
    name == ":"
        || (name.starts_with(':')
            && name[1..].split(':').all(|part| {
                !part.is_empty()
                    && part.chars().all(|character| {
                        character.is_ascii_alphanumeric() || "_-.$".contains(character)
                    })
            }))
}
fn valid_variant(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || "_-".contains(character))
}

/// Evaluated directory provenance captured from one current, trusted Gradle root.
///
/// This immutable value cannot detect later store changes by itself. Callers must
/// check `is_current` before dispatch and before applying a parsed model.
#[derive(Clone)]
pub struct EvaluatedModelPaths {
    root: PathBuf,
    token: crate::project_context::RootToken,
    modules: BTreeMap<String, PathBuf>,
}

impl EvaluatedModelPaths {
    pub fn capture(
        store: &crate::project_context::ContextStore,
        token: &crate::project_context::RootToken,
        root: &Path,
    ) -> Result<Self> {
        use crate::project_context::{ModuleOwner, ObservationPhase};
        ensure!(
            store.is_current(token),
            "Evaluated model paths require a current trusted root"
        );
        let handle = store
            .handles()
            .find(|handle| store.token(*handle).as_ref() == Some(token))
            .context("Evaluated model root was removed")?;
        let snapshot = store
            .snapshot(handle)
            .context("Import the evaluated project context first")?;
        ensure!(
            store.root_path(handle) == Some(root)
                && snapshot.root() == root
                && snapshot.phase() == ObservationPhase::Complete,
            "Evaluated model paths belong to an incomplete or different root"
        );
        let mut modules = BTreeMap::new();
        for module in snapshot.modules() {
            ensure!(
                matches!(snapshot.module_owner(module.directory()), ModuleOwner::Module(owner) if owner == module.path()),
                "Evaluated module {} has ambiguous directory ownership",
                module.path()
            );
            modules.insert(module.path().to_owned(), module.directory().to_path_buf());
        }
        Ok(Self {
            root: root.to_path_buf(),
            token: token.clone(),
            modules,
        })
    }

    pub fn is_current(&self, store: &crate::project_context::ContextStore) -> bool {
        store.is_current(&self.token)
    }
}

pub fn parse_model(output: &str, root: &Path) -> Result<ProjectModel> {
    parse_model_with_paths(output, root, None)
}

/// Parse paths proven by evaluated Gradle module getters. The caller retains
/// responsibility for rejecting a result after the captured context expires.
pub fn parse_model_with_context(
    output: &str,
    root: &Path,
    paths: &EvaluatedModelPaths,
) -> Result<ProjectModel> {
    ensure!(
        paths.root == root,
        "Evaluated model paths belong to a different root"
    );
    parse_model_with_paths(output, root, Some(paths))
}

fn parse_model_with_paths(
    output: &str,
    root: &Path,
    paths: Option<&EvaluatedModelPaths>,
) -> Result<ProjectModel> {
    let mut records = output.lines().filter_map(|line| line.strip_prefix(OUTPUT));
    let exported: ExportedProjectModel = serde_json::from_str(
        records
            .next()
            .context("Gradle returned no Android project model")?,
    )?;
    ensure!(
        records.next().is_none(),
        "Gradle returned multiple Android project models"
    );
    let model = ProjectModel {
        version: exported.version,
        root: exported.root,
        modules: exported
            .modules
            .into_iter()
            .map(ExportedModule::into_module)
            .collect::<Result<_>>()?,
        diagnostics: exported.diagnostics,
    };
    ensure!(
        model.version == 1,
        "Unsupported Android project model version {}",
        model.version
    );
    let root = root.canonicalize()?;
    ensure!(
        model.root == root,
        "The Android model belongs to a different project"
    );
    let mut modules = BTreeSet::new();
    for module in &model.modules {
        ensure!(
            valid_module(&module.path) && modules.insert(&module.path),
            "Invalid or duplicate Android module {}",
            module.path
        );
        let boundary = if let Some(paths) = paths {
            let directory = paths
                .modules
                .get(&module.path)
                .context("Android model module has no evaluated directory provenance")?;
            ensure!(
                module.directory == *directory
                    && directory.is_absolute()
                    && directory.canonicalize()? == *directory,
                "Android model module {} does not match its evaluated canonical directory",
                module.path
            );
            if directory.starts_with(&root) {
                root.as_path()
            } else {
                directory.as_path()
            }
        } else {
            ensure!(
                module.directory.is_absolute()
                    && module.directory.canonicalize()?.starts_with(&root),
                "Module {} is outside the selected build; included builds and external project directories are unsupported",
                module.path
            );
            root.as_path()
        };
        if let Some(catalog) = &module.source_providers {
            let mut providers = BTreeSet::new();
            for provider in &catalog.providers {
                ensure!(
                    !provider.name.trim().is_empty()
                        && !provider.name.chars().any(char::is_control)
                        && providers.insert(&provider.name),
                    "Invalid or duplicate source provider in Android module {}",
                    module.path
                );
                for source in &provider.roots {
                    validate_project_path(&source.path, boundary)?;
                }
            }
        }
        let mut variants = BTreeSet::new();
        ensure!(
            module.default_variant.as_ref().is_none_or(|default| {
                module
                    .variants
                    .iter()
                    .any(|variant| &variant.name == default)
            }),
            "Default variant is absent from Android module {}",
            module.path
        );
        for variant in &module.variants {
            ensure!(
                valid_variant(&variant.name) && variants.insert(&variant.name),
                "Invalid or duplicate Android variant {}",
                variant.name
            );
            ensure!(
                variant
                    .components
                    .iter()
                    .filter(|component| component.scope == SourceScope::Main)
                    .count()
                    == 1,
                "Android variant {} must contain exactly one main component",
                variant.name
            );
            let mut components = BTreeSet::new();
            for component in &variant.components {
                ensure!(
                    valid_variant(&component.name) && components.insert(&component.name),
                    "Invalid or duplicate Android component {}",
                    component.name
                );
                for source in &component.sources {
                    validate_project_path(&source.path, boundary)?;
                }
                for dependency in &component.dependencies {
                    if let Dependency::Project { module, variant } = dependency {
                        ensure!(
                            model
                                .variant(&VariantId {
                                    module: module.clone(),
                                    variant: variant.clone()
                                })
                                .is_some(),
                            "Dependency {module}:{variant} is absent from the Android project model"
                        );
                    }
                }
            }
            if let Some(path) = &variant.output_listing {
                validate_project_path(path, boundary)?;
            }
        }
    }
    ensure!(
        model
            .modules
            .iter()
            .any(|module| module.kind != ModuleKind::Jvm),
        "No supported Android modules were found"
    );
    Ok(model)
}

fn validate_project_path(path: &Path, root: &Path) -> Result<()> {
    ensure!(
        path.is_absolute()
            && path.starts_with(root)
            && !path
                .components()
                .any(|part| matches!(part, PathComponent::ParentDir)),
        "Android model path is outside the selected project: {}",
        path.display()
    );
    // Generated roots may not exist until their producer has run. Resolve the nearest
    // existing ancestor so missing paths cannot bypass the symlink boundary check.
    let ancestor = path
        .ancestors()
        .find(|ancestor| ancestor.exists())
        .context("Android model path has no existing ancestor")?;
    ensure!(
        ancestor.canonicalize()?.starts_with(root),
        "Android model path escapes the project through a symlink: {}",
        path.display()
    );
    Ok(())
}

pub fn prepare() -> Result<tempfile::TempDir> {
    let directory = tempfile::Builder::new()
        .prefix("koda-android-model-")
        .tempdir()?;
    atomic_write(&directory.path().join("export.gradle"), EXPORT, false)?;
    Ok(directory)
}

fn selection_directory(root: &Path) -> Result<PathBuf> {
    ensure_directory(&root.join(".koda"))?;
    let cache = root.join(".koda/android-model");
    if cache.exists() {
        ensure_directory(&cache)?;
        ensure!(
            fs::read_to_string(cache.join(".gitignore"))? == MARKER,
            "The .koda/android-model directory contains unmanaged files; move it aside before syncing"
        );
    } else {
        ensure_directory(&cache)?;
        atomic_write(&cache.join(".gitignore"), MARKER, false)?;
    }
    Ok(cache)
}

pub fn install_selection(root: &Path, selected: &SelectedProject) -> Result<PathBuf> {
    ensure!(
        selected.model.root == root.canonicalize()?,
        "The Android selection belongs to a different project"
    );
    let cache = selection_directory(root)?;
    let path = cache.join("selected.json");
    atomic_write(
        &path,
        &serde_json::to_string(&selected.projection())?,
        false,
    )?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    // These eight cases are adapted from AOSP DefaultVariantsTest.kt,
    // Copyright (C) 2022 The Android Open Source Project, Apache-2.0.
    // The original inline fixtures and assertions are retained in test_data/default_variants.
    fn default_variant_fixture(build_type: Option<&str>, flavors: &[&str]) -> VariantDefinition {
        let mut name = String::new();
        for part in flavors.iter().copied().chain(build_type) {
            if name.is_empty() {
                name.push_str(part);
            } else {
                let mut characters = part.chars();
                if let Some(first) = characters.next() {
                    name.extend(first.to_uppercase());
                    name.extend(characters);
                }
            }
        }
        VariantDefinition {
            name,
            build_type: build_type.map(str::to_owned),
            product_flavors: flavors.iter().map(|flavor| (*flavor).to_owned()).collect(),
        }
    }

    fn assert_reference_default_variant(test: &str) -> Result<()> {
        #[derive(Deserialize)]
        struct Cases {
            cases: Vec<Case>,
        }
        #[derive(Deserialize)]
        struct Case {
            test: String,
            variants: Vec<ReferenceVariant>,
            user_preferred_build_types: BTreeSet<String>,
            user_preferred_product_flavors: BTreeSet<String>,
            expected: Option<String>,
        }
        #[derive(Deserialize)]
        struct ReferenceVariant {
            name: String,
            build_type: Option<String>,
            product_flavors: Vec<String>,
        }
        let cases: Cases = serde_json::from_str(include_str!(
            "../test_data/default_variants/DefaultVariantsTest.cases.json"
        ))?;
        let case = cases
            .cases
            .into_iter()
            .find(|case| case.test == test)
            .with_context(|| format!("Missing upstream DefaultVariantsTest case {test}"))?;
        let variants = case
            .variants
            .into_iter()
            .map(|variant| VariantDefinition {
                name: variant.name,
                build_type: variant.build_type,
                product_flavors: variant.product_flavors,
            })
            .collect::<Vec<_>>();
        assert_eq!(
            default_variant(
                &variants,
                &case.user_preferred_build_types,
                &case.user_preferred_product_flavors,
            ),
            case.expected.as_deref(),
            "upstream DefaultVariantsTest.{test}"
        );
        Ok(())
    }

    #[test]
    fn default_variants_one_variant() -> Result<()> {
        assert_reference_default_variant("oneVariant")
    }

    #[test]
    fn default_variants_debug_preferred() -> Result<()> {
        assert_reference_default_variant("debugPreferred")
    }

    #[test]
    fn default_variants_preferred_build_type() -> Result<()> {
        assert_reference_default_variant("preferredBuildType")
    }

    #[test]
    fn default_variants_preferred_product_flavor_over_debug_build_type() -> Result<()> {
        assert_reference_default_variant("preferredProductFlavorOverDebugBuildType")
    }

    #[test]
    fn default_variants_preferred_flavors_in_two_dimensions() -> Result<()> {
        assert_reference_default_variant("preferredFlavorsInTwoDimensions")
    }

    #[test]
    fn default_variants_preferred_flavor_in_second_dimension_only() -> Result<()> {
        assert_reference_default_variant("preferredFlavorInSecondDimensionOnly")
    }

    #[test]
    fn default_variants_mismatched_product_flavour_length() -> Result<()> {
        assert_reference_default_variant("mismatchedProductFlavourLength")
    }

    #[test]
    fn default_variants_on_empty() -> Result<()> {
        assert_reference_default_variant("onEmpty")
    }

    #[test]
    fn default_variant_ties_null_types_and_lexical_fallbacks() {
        let variants = [
            default_variant_fixture(Some("release"), &["aB", "a"]),
            default_variant_fixture(Some("release"), &["a", "z"]),
            default_variant_fixture(Some("staging"), &["a", "a"]),
            default_variant_fixture(Some("release"), &["a", "a"]),
        ];
        assert_eq!(
            default_variant(&variants, &BTreeSet::new(), &BTreeSet::new()),
            Some("aARelease")
        );
        let variants = [
            default_variant_fixture(Some("release"), &["foo"]),
            default_variant_fixture(None, &["foo"]),
        ];
        assert_eq!(
            default_variant(&variants, &BTreeSet::new(), &BTreeSet::new()),
            Some("foo")
        );
        let variants = [
            default_variant_fixture(Some("release"), &["\u{e000}"]),
            default_variant_fixture(Some("release"), &["\u{10000}"]),
        ];
        assert_eq!(
            default_variant(&variants, &BTreeSet::new(), &BTreeSet::new()),
            Some("\u{10000}Release")
        );
        let variants = [
            default_variant_fixture(Some("\u{e000}"), &["foo"]),
            default_variant_fixture(Some("\u{10000}"), &["foo"]),
        ];
        assert_eq!(
            default_variant(&variants, &BTreeSet::new(), &BTreeSet::new()),
            Some("foo\u{10000}")
        );
        let mut tied = default_variant_fixture(None, &["foo"]);
        tied.name = "other".into();
        let variants = [default_variant_fixture(None, &["foo"]), tied];
        assert_eq!(
            default_variant(&variants, &BTreeSet::new(), &BTreeSet::new()),
            Some("foo")
        );
    }

    #[test]
    fn exported_default_variant_metadata_is_selected_in_rust_and_validated() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let application = model
            .modules
            .iter_mut()
            .find(|module| module.kind == ModuleKind::Application)
            .context("Application module")?;
        application.variants = vec![variant("fooDebug", vec![]), variant("barRelease", vec![])];
        for variant in &mut application.variants {
            variant.output_listing = Some(
                root.join("app/build")
                    .join(&variant.name)
                    .join("output-metadata.json"),
            );
        }
        model
            .modules
            .retain(|module| module.kind == ModuleKind::Application);
        let mut exported = serde_json::to_value(&model)?;
        let application = exported
            .get_mut("modules")
            .and_then(serde_json::Value::as_array_mut)
            .and_then(|modules| modules.first_mut())
            .and_then(serde_json::Value::as_object_mut)
            .context("Exported application")?;
        application.insert(
            "defaultVariantSelection".into(),
            serde_json::json!({
                "multiplatform": false,
                "preferredBuildTypes": [],
                "preferredProductFlavors": ["bar"],
                "variants": [
                    {"name": "fooDebug", "buildType": "debug", "productFlavors": ["foo"]},
                    {"name": "barRelease", "buildType": "release", "productFlavors": ["bar"]}
                ]
            }),
        );
        let record = |exported: &serde_json::Value| format!("{OUTPUT}{exported}");
        let parsed = parse_model(&record(&exported), &root)?;
        assert_eq!(
            parsed.default_target().context("Default target")?.variant,
            "barRelease"
        );
        assert!(!serde_json::to_string(&parsed)?.contains("defaultVariantSelection"));
        let application = exported
            .get_mut("modules")
            .and_then(serde_json::Value::as_array_mut)
            .and_then(|modules| modules.first_mut())
            .context("Exported application")?;
        application["defaultVariantSelection"]["multiplatform"] = true.into();
        assert_eq!(
            parse_model(&record(&exported), &root)?
                .default_target()
                .context("Multiplatform target")?
                .variant,
            "fooDebug"
        );
        let application = exported
            .get_mut("modules")
            .and_then(serde_json::Value::as_array_mut)
            .and_then(|modules| modules.first_mut())
            .context("Exported application")?;
        application["defaultVariantSelection"]["variants"][0]["name"] = "removedDebug".into();
        assert!(parse_model(&record(&exported), &root).is_err());
        Ok(())
    }

    fn component(
        name: &str,
        scope: SourceScope,
        dependencies: Vec<Dependency>,
        sources: Vec<SourceRoot>,
    ) -> Component {
        Component {
            name: name.into(),
            namespace: None,
            scope,
            dependencies,
            sources,
        }
    }
    fn variant(name: &str, dependencies: Vec<Dependency>) -> Variant {
        Variant {
            name: name.into(),
            output_listing: None,
            components: vec![component(name, SourceScope::Main, dependencies, Vec::new())],
        }
    }
    fn dependency(module: &str, variant: &str) -> Dependency {
        Dependency::Project {
            module: module.into(),
            variant: variant.into(),
        }
    }

    fn fixture(root: &Path) -> Result<ProjectModel> {
        for module in ["app", "library", "feature", "testing"] {
            fs::create_dir_all(root.join(module))?;
        }
        let mut application = variant(
            "paidDebug",
            vec![
                dependency(":library", "freeRelease"),
                dependency(":feature", "paidDebug"),
            ],
        );
        application.output_listing =
            Some(root.join("app/build/outputs/apk/paid/debug/output-metadata.json"));
        application.components[0].sources = vec![
            SourceRoot {
                path: root.join("app/src/main/java"),
                kind: SourceKind::Java,
                generated: false,
            },
            SourceRoot {
                path: root.join("app/src/paid/kotlin"),
                kind: SourceKind::Kotlin,
                generated: false,
            },
            SourceRoot {
                path: root.join("app/build/generated/ksp/paidDebug/kotlin"),
                kind: SourceKind::Kotlin,
                generated: true,
            },
            SourceRoot {
                path: root.join("app/src/paid/res"),
                kind: SourceKind::Resources,
                generated: false,
            },
        ];
        application.components.push(component(
            "paidDebugUnitTest",
            SourceScope::UnitTest,
            vec![
                dependency(":testing", "jvm"),
                Dependency::External {
                    coordinate: "junit:junit:4.13.2".into(),
                },
            ],
            vec![SourceRoot {
                path: root.join("app/src/test/java"),
                kind: SourceKind::Java,
                generated: false,
            }],
        ));
        application.components.push(component(
            "paidDebugAndroidTest",
            SourceScope::AndroidTest,
            vec![],
            vec![],
        ));
        application.components.push(component(
            "paidDebugTestFixtures",
            SourceScope::TestFixtures,
            vec![],
            vec![],
        ));
        let module = |name: &str, kind, variants| Module {
            path: format!(":{name}"),
            directory: root.join(name),
            namespace: Some(format!("dev.{name}")),
            kind,
            default_variant: None,
            source_providers: None,
            evaluated_providers: None,
            variants,
        };
        Ok(ProjectModel {
            version: 1,
            root: root.to_path_buf(),
            diagnostics: Vec::new(),
            modules: vec![
                module(
                    "app",
                    ModuleKind::Application,
                    vec![application, variant("freeDebug", vec![])],
                ),
                module(
                    "library",
                    ModuleKind::Library,
                    vec![variant("freeRelease", vec![]), variant("freeDebug", vec![])],
                ),
                module(
                    "feature",
                    ModuleKind::DynamicFeature,
                    vec![variant("paidDebug", vec![dependency(":app", "paidDebug")])],
                ),
                module("testing", ModuleKind::Jvm, vec![variant("jvm", vec![])]),
            ],
        })
    }
    fn output(model: &ProjectModel) -> Result<String> {
        Ok(format!(
            "Gradle noise\n{OUTPUT}{}\nBUILD SUCCESSFUL",
            serde_json::to_string(model)?
        ))
    }

    #[test]
    fn evaluated_variant_sources_retain_sdk_generation_flags_and_order() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        fs::create_dir(root.join("app"))?;
        let mut captured: serde_json::Value = serde_json::from_str(include_str!(
            "../test_data/source_providers/gradle-smoke-generation/model.json"
        ))?;
        fn relocate(value: &mut serde_json::Value, root: &Path) {
            match value {
                serde_json::Value::String(path) => {
                    if let Some(relative) = path.strip_prefix("${project_root}") {
                        *path = root
                            .join(relative.trim_start_matches('/'))
                            .to_string_lossy()
                            .into_owned();
                    }
                }
                serde_json::Value::Array(values) => {
                    for value in values {
                        relocate(value, root);
                    }
                }
                serde_json::Value::Object(values) => {
                    for value in values.values_mut() {
                        relocate(value, root);
                    }
                }
                _ => {}
            }
        }
        relocate(&mut captured, &root);
        let parsed = parse_model(&format!("{OUTPUT}{captured}"), &root)?;
        let application = parsed.modules.first().context("Captured app module")?;
        assert_eq!(
            application
                .variants
                .iter()
                .map(|variant| variant.name.as_str())
                .collect::<Vec<_>>(),
            ["demoDebug", "demoRelease"]
        );
        for variant in &application.variants {
            let main = variant
                .components
                .iter()
                .find(|component| component.scope == SourceScope::Main)
                .context("Captured main component")?;
            for (kind, suffix) in [
                (SourceKind::Java, "java"),
                (SourceKind::Kotlin, "kotlin"),
                (SourceKind::Resources, "res"),
                (SourceKind::Assets, "assets"),
            ] {
                let path = root.join(format!("app/src/{}/{suffix}", variant.name));
                assert!(!path.exists());
                let source = main
                    .sources
                    .iter()
                    .find(|source| source.kind == kind && source.path == path)
                    .context("Missing variant-only configured root")?;
                assert!(!source.generated, "Configured {kind:?} root: {path:?}");
            }
            let assets = main
                .sources
                .iter()
                .filter(|source| source.kind == SourceKind::Assets)
                .map(|source| {
                    assert!(!source.path.exists());
                    Ok((
                        source.path.strip_prefix(&root)?.to_path_buf(),
                        source.generated,
                    ))
                })
                .collect::<Result<Vec<_>>>()?;
            let mut expected = vec![
                (
                    format!("app/generated-outside-build/{}", variant.name),
                    true,
                ),
                (format!("app/src/{}/assets", variant.name), false),
                ("app/late-static-assets".into(), false),
                ("app/build/late-static-assets".into(), false),
            ];
            if variant.name == "demoDebug" {
                expected.extend([
                    ("app/unrelated-assets".into(), false),
                    ("app/unrelated-assets/nested".into(), false),
                    ("app/flavor-assets".into(), false),
                ]);
            } else {
                expected.extend([
                    ("app/src/release/assets".into(), false),
                    ("app/flavor-assets".into(), false),
                    ("app/unrelated-assets".into(), false),
                ]);
            }
            assert_eq!(
                assets,
                expected
                    .into_iter()
                    .map(|(path, generated)| (PathBuf::from(path), generated))
                    .collect::<Vec<_>>()
            );
            assert!(
                main.sources
                    .iter()
                    .all(|source| !source.path.starts_with(root.join("app/inactive-assets")))
            );
        }
        let inactive = application
            .source_providers
            .as_ref()
            .context("Captured configured provider catalog")?
            .providers
            .iter()
            .find(|provider| provider.name == "inactive")
            .context("Disabled flavor retained in configured catalog")?;
        assert!(
            inactive
                .roots
                .iter()
                .any(|source| source.kind == SourceProviderRootKind::Assets
                    && source.path == root.join("app/inactive-assets"))
        );
        Ok(())
    }

    #[test]
    fn legacy_provider_metadata_stays_unknown_and_assets_retain_missing_roots() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let generated_assets = root.join("app/build/generated/assets/createAssets");
        model.modules[0].variants[0].components[0]
            .sources
            .push(SourceRoot {
                path: generated_assets.clone(),
                kind: SourceKind::Assets,
                generated: true,
            });
        let mut legacy = serde_json::to_value(&model)?;
        for module in legacy["modules"].as_array_mut().context("Module array")? {
            let removed = module
                .as_object_mut()
                .context("Module object")?
                .remove("sourceProviders");
            assert!(removed.is_some());
        }
        let parsed = parse_model(&format!("{OUTPUT}{legacy}"), &root)?;
        let application = parsed.modules.first().context("Application module")?;
        assert!(application.source_providers.is_none());
        assert!(
            application
                .source_provider_candidates(&root.join("app/src/main/res/resources.properties"))
                .is_none()
        );
        assert!(!generated_assets.exists());
        assert!(
            application.variants[0].components[0]
                .sources
                .iter()
                .any(|source| source.kind == SourceKind::Assets
                    && source.generated
                    && source.path == generated_assets)
        );
        model.modules[0].source_providers = Some(SourceProviderCatalog {
            order: SourceProviderOrder::GradleSourceSetIteration,
            providers: Vec::new(),
        });
        let parsed = parse_model(&output(&model)?, &root)?;
        assert_eq!(
            parsed.modules[0]
                .source_provider_candidates(&generated_assets)
                .context("Known configured catalog")?
                .len(),
            0
        );
        Ok(())
    }

    #[test]
    fn provider_candidates_preserve_names_order_and_shared_nested_ambiguity() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let shared = root.join("app/unrelated-location");
        let nested = shared.join("nested");
        let manifest = root.join("app/custom-manifest/manifest.xml");
        model.modules[0].source_providers = Some(SourceProviderCatalog {
            order: SourceProviderOrder::GradleSourceSetIteration,
            providers: vec![
                SourceProvider {
                    name: "release".into(),
                    roots: vec![SourceProviderRoot {
                        path: shared.clone(),
                        kind: SourceProviderRootKind::Resources,
                    }],
                },
                SourceProvider {
                    name: "main".into(),
                    roots: vec![
                        SourceProviderRoot {
                            path: nested.clone(),
                            kind: SourceProviderRootKind::Assets,
                        },
                        SourceProviderRoot {
                            path: shared.clone(),
                            kind: SourceProviderRootKind::Java,
                        },
                        SourceProviderRoot {
                            path: shared,
                            kind: SourceProviderRootKind::Kotlin,
                        },
                        SourceProviderRoot {
                            path: manifest.clone(),
                            kind: SourceProviderRootKind::Manifest,
                        },
                    ],
                },
            ],
        });
        let parsed = parse_model(&output(&model)?, &root)?;
        let application = parsed.modules.first().context("Application module")?;
        let catalog = application
            .source_providers
            .as_ref()
            .context("Provider catalog")?;
        assert_eq!(
            catalog,
            model.modules[0]
                .source_providers
                .as_ref()
                .context("Input catalog")?
        );
        let candidates = application
            .source_provider_candidates(&nested.join("resources.properties"))
            .context("Known catalog")?;
        assert_eq!(
            candidates
                .iter()
                .map(|provider| provider.name.as_str())
                .collect::<Vec<_>>(),
            ["release", "main"]
        );
        for path in [
            manifest.as_path(),
            manifest.parent().context("Manifest parent")?,
        ] {
            assert_eq!(
                application
                    .source_provider_candidates(path)
                    .context("Known catalog")?
                    .iter()
                    .map(|provider| provider.name.as_str())
                    .collect::<Vec<_>>(),
                ["main"]
            );
        }
        assert!(
            application
                .source_provider_candidates(&manifest.join("child"))
                .context("Known catalog")?
                .is_empty()
        );
        assert!(
            application
                .source_provider_candidates(&root.join("app/src/main/res"))
                .context("Known catalog")?
                .is_empty()
        );
        Ok(())
    }

    #[test]
    fn rejects_invalid_provider_names_duplicates_and_escaping_roots() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let provider = SourceProvider {
            name: "main".into(),
            roots: vec![SourceProviderRoot {
                path: root.join("app/custom-assets"),
                kind: SourceProviderRootKind::Assets,
            }],
        };
        model.modules[0].source_providers = Some(SourceProviderCatalog {
            order: SourceProviderOrder::GradleSourceSetIteration,
            providers: vec![provider.clone(), provider.clone()],
        });
        assert!(parse_model(&output(&model)?, &root).is_err());
        for name in ["", " ", "main\nother"] {
            model.modules[0].source_providers = Some(SourceProviderCatalog {
                order: SourceProviderOrder::GradleSourceSetIteration,
                providers: vec![SourceProvider {
                    name: name.into(),
                    ..provider.clone()
                }],
            });
            assert!(parse_model(&output(&model)?, &root).is_err());
        }
        for path in [
            PathBuf::from("relative/assets"),
            root.join("app/../../outside-assets"),
        ] {
            model.modules[0].source_providers = Some(SourceProviderCatalog {
                order: SourceProviderOrder::GradleSourceSetIteration,
                providers: vec![SourceProvider {
                    roots: vec![SourceProviderRoot {
                        path,
                        kind: SourceProviderRootKind::Assets,
                    }],
                    ..provider.clone()
                }],
            });
            assert!(parse_model(&output(&model)?, &root).is_err());
        }
        #[cfg(unix)]
        {
            let outside = tempfile::tempdir()?;
            std::os::unix::fs::symlink(outside.path(), root.join("app/escaped"))?;
            model.modules[0].source_providers = Some(SourceProviderCatalog {
                order: SourceProviderOrder::GradleSourceSetIteration,
                providers: vec![SourceProvider {
                    roots: vec![SourceProviderRoot {
                        path: root.join("app/escaped/missing/assets"),
                        kind: SourceProviderRootKind::Assets,
                    }],
                    ..provider
                }],
            });
            assert!(parse_model(&output(&model)?, &root).is_err());
        }
        Ok(())
    }

    #[test]
    fn module_default_is_validated_and_selects_fresh_application_artifacts() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let application = model
            .modules
            .iter_mut()
            .find(|module| module.kind == ModuleKind::Application)
            .context("Application module")?;
        let mut release = variant("freeRelease", vec![]);
        release.output_listing = Some(root.join("app/build/freeRelease/output-metadata.json"));
        application.variants.push(release);
        application.default_variant = Some("freeRelease".into());
        let parsed = parse_model(&output(&model)?, &root)?;
        assert_eq!(
            parsed.default_target(),
            Some(AndroidTarget {
                module: ":app".into(),
                variant: "freeRelease".into(),
                output_listing: root.join("app/build/freeRelease/output-metadata.json"),
            })
        );
        let application = model
            .modules
            .iter_mut()
            .find(|module| module.kind == ModuleKind::Application)
            .context("Application module")?;
        application.default_variant = Some("removedRelease".into());
        assert!(parse_model(&output(&model)?, &root).is_err());
        let application = model
            .modules
            .iter_mut()
            .find(|module| module.kind == ModuleKind::Application)
            .context("Application module")?;
        application.default_variant = None;
        assert!(
            parse_model(&output(&model)?, &root)?
                .default_target()
                .is_none()
        );
        Ok(())
    }

    #[test]
    fn flavor_fallbacks_tests_dynamic_features_and_missing_generated_roots() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let model = Arc::new(parse_model(&output(&fixture(&root)?)?, &root)?);
        let target = model
            .targets()
            .into_iter()
            .next()
            .context("Expected an application target")?;
        assert_eq!(target.module, ":app");
        assert_eq!(target.variant, "paidDebug");
        let selected = model.select(VariantId::from(&target))?;
        assert_eq!(
            selected.variants.get(":library").map(String::as_str),
            Some("freeRelease")
        );
        assert_eq!(
            selected.variants.get(":testing").map(String::as_str),
            Some("jvm")
        );
        assert_eq!(
            selected.kotlin_variants(),
            ":app=paidDebug;:feature=paidDebug;:library=freeRelease"
        );
        assert_eq!(selected.modules().count(), 4);
        assert!(
            !selected
                .visible_modules(":app", SourceScope::Main)
                .contains(":testing")
        );
        assert!(
            selected
                .visible_modules(":app", SourceScope::UnitTest)
                .contains(":testing")
        );
        assert!(
            !selected
                .visible_modules(":app", SourceScope::AndroidTest)
                .contains(":testing")
        );
        assert!(
            !selected
                .visible_modules(":app", SourceScope::Main)
                .contains(":feature")
        );
        assert!(
            selected
                .visible_modules(":feature", SourceScope::Main)
                .contains(":app")
        );
        selected.validate_target(&target)?;
        assert!(
            selected
                .validate_target(&AndroidTarget {
                    variant: "freeDebug".into(),
                    ..target
                })
                .is_err()
        );
        let (_, variant) = model
            .variant(&selected.selected)
            .context("Expected the selected variant")?;
        assert_eq!(variant.components.len(), 4);
        assert!(
            variant.components[0]
                .sources
                .iter()
                .any(|source| source.generated && !source.path.exists())
        );
        assert!(!variant.components[0].dependencies.iter().any(|dependency| matches!(dependency, Dependency::External { coordinate } if coordinate.contains("junit"))));
        Ok(())
    }

    #[test]
    fn rejects_conflicting_test_dependency_variants_and_removed_variants() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        model.modules[0].variants[0].components[1]
            .dependencies
            .push(dependency(":library", "freeDebug"));
        let model = Arc::new(parse_model(&output(&model)?, &root)?);
        let error = model
            .select(VariantId {
                module: ":app".into(),
                variant: "paidDebug".into(),
            })
            .expect_err("Conflicting main/test library variants should fail");
        assert!(error.to_string().contains("multiple variants"));
        assert!(
            model
                .select(VariantId {
                    module: ":app".into(),
                    variant: "removedDebug".into()
                })
                .is_err()
        );
        Ok(())
    }

    #[test]
    fn rejects_outdated_sync_variant_aba_failed_sync_and_project_aba() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut state = ModelState::default();
        let first_sync = state.invalidate(Some(root.clone()));
        state.publish(&first_sync, fixture(&root)?)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        let first_variant = state.token();
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "freeDebug".into(),
        }))?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        assert!(!state.is_current(&first_variant));
        let failed_sync = state.invalidate(Some(root.clone()));
        assert!(state.model.is_none() && state.selected.is_none());
        assert!(state.publish(&first_sync, fixture(&root)?).is_err());
        let recovery = state.invalidate(Some(root.clone()));
        assert!(state.publish(&failed_sync, fixture(&root)?).is_err());
        state.publish(&recovery, fixture(&root)?)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        let old_project = state.token();
        state.invalidate(None);
        state.invalidate(Some(root));
        assert!(!state.is_current(&old_project));
        Ok(())
    }

    #[test]
    fn validates_model_schema_duplicate_records_paths_and_owned_cache() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let mut model = fixture(&root)?;
        let record = output(&model)?;
        assert!(parse_model(&(record.clone() + "\n" + &record), &root).is_err());
        model.version = 2;
        assert!(parse_model(&output(&model)?, &root).is_err());
        model.version = 1;
        model.modules.push(model.modules[0].clone());
        assert!(parse_model(&output(&model)?, &root).is_err());
        model.modules.pop();
        model.modules[0].variants[0].components[0].sources[0].path = root.join("../escape/missing");
        assert!(parse_model(&output(&model)?, &root).is_err());
        #[cfg(unix)]
        {
            let outside = tempfile::tempdir()?;
            std::os::unix::fs::symlink(outside.path(), root.join("escaped"))?;
            model.modules[0].variants[0].components[0].sources[0].path =
                root.join("escaped/not-created");
            assert!(parse_model(&output(&model)?, &root).is_err());
        }
        let cache = root.join(".koda/android-model");
        fs::create_dir_all(&cache)?;
        fs::write(cache.join(".gitignore"), "user files")?;
        assert!(selection_directory(&root).is_err());
        assert_eq!(fs::read_to_string(cache.join(".gitignore"))?, "user files");
        fs::rename(&cache, root.join("user-cache"))?;
        assert!(selection_directory(&root)?.is_dir());
        assert!(selection_directory(&root)?.is_dir());
        Ok(())
    }

    #[test]
    fn exporters_are_request_owned_and_selection_does_not_write_a_project_script() -> Result<()> {
        let first = prepare()?;
        let second = prepare()?;
        assert_ne!(first.path(), second.path());
        let first_script = first.path().join("export.gradle");
        assert_eq!(fs::read_to_string(&first_script)?, EXPORT);
        drop(first);
        assert!(!first_script.exists());
        assert!(second.path().join("export.gradle").is_file());

        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let selected = Arc::new(fixture(&root)?).select(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        })?;
        let selection = install_selection(&root, &selected)?;
        assert_eq!(selection, root.join(".koda/android-model/selected.json"));
        assert!(!root.join(".koda/android-model/export.gradle").exists());
        let legacy_script = root.join(".koda/android-model/export.gradle");
        fs::write(&legacy_script, "legacy exporter sentinel")?;
        let request = prepare()?;
        install_selection(&root, &selected)?;
        assert_eq!(
            fs::read_to_string(legacy_script)?,
            "legacy exporter sentinel"
        );
        assert_eq!(
            fs::read_to_string(request.path().join("export.gradle"))?,
            EXPORT
        );
        assert_eq!(
            serde_json::from_str::<serde_json::Value>(&fs::read_to_string(selection)?)?,
            serde_json::to_value(selected.projection())?
        );
        Ok(())
    }

    #[test]
    fn java_and_preview_adapters_use_the_selected_graph_and_component_scopes() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let model = Arc::new(fixture(&root)?);
        let selected = model.select(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        })?;
        let (_, selection) = crate::java::prepare_selected(&root, &selected)?;
        let projection: serde_json::Value = serde_json::from_str(&fs::read_to_string(selection)?)?;
        let components = projection[0]["components"]
            .as_array()
            .context("Missing components")?;
        assert_eq!(components.len(), 4);
        assert_eq!(components[1]["scope"], "unitTest");
        let java_modules = selected
            .modules()
            .map(|(module, variant)| crate::java::JavaModule {
                project: module.path.clone(),
                variant: variant.name.clone(),
                directory: module.directory.clone(),
                source_compatibility: "11".into(),
                target_compatibility: "11".into(),
                sources: vec![],
                libraries: vec![],
                test_sources: vec![],
                test_libraries: vec![],
            })
            .collect::<Vec<_>>();
        crate::java::validate_selection(&java_modules, &selected)?;
        assert!(crate::java::validate_selection(&java_modules[1..], &selected).is_err());
        let mut wrong_java = java_modules;
        wrong_java[0]
            .test_sources
            .push(root.join("app/src/free/java"));
        assert!(crate::java::validate_selection(&wrong_java, &selected).is_err());
        let mut preview = crate::preview::Model {
            module: ":app".into(),
            variant: "paidDebug".into(),
            namespace: "dev.app".into(),
            class_path: vec![],
            project_class_path: vec![],
            preview_class_path: vec![],
            source_files: vec![],
        };
        crate::preview::validate_selection(&preview, &selected)?;
        preview.namespace = "dev.previous".into();
        assert!(crate::preview::validate_selection(&preview, &selected).is_err());
        Ok(())
    }
    #[cfg(unix)]
    #[test]
    fn publish_model_for_a_symlink_opened_root() -> Result<()> {
        let temporary = tempfile::tempdir()?;
        let root = temporary.path().canonicalize()?;
        let alias = root.join("project-alias");
        let project = root.join("project");
        fs::create_dir(&project)?;
        std::os::unix::fs::symlink(&project, &alias)?;
        let mut state = ModelState::default();
        let token = state.invalidate(Some(alias));
        let model = fixture(&project)?;
        state.publish(&token, model)?;
        state.select(Some(VariantId {
            module: ":app".into(),
            variant: "paidDebug".into(),
        }))?;
        assert!(state.selected.is_some());
        Ok(())
    }
}
