name: Release Koda Dev (prerelease)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/macos_release.yml
    with:
      channel: dev
